server:
    servlet:
        contextPath: /buff/common/utils
        session:
            cookie: {secure: true}
    port: 8080
spring.servlet.multipart:
    enabled: true
    max-file-size: 10MB
    max-request-size: 15MB
spring:
    env:
        type: default
    search:
        service:
            url: http://localhost:8080/buff/common/utils
    skill-builder:
        service:
            url: http://localhost:8080/buff/common/utils
    logger:
        url: http://localhost:8080/buff/common/utils